spring:
  application:
    name: Alunos API
  datasource:
    url: jdbc:h2:mem:alunos
    username: sa
    password: manager
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console